from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

# number of row
num_rows = 1000

skill_descriptions = {
    'Programming': 'The process of writing code to create software applications. Learn through coding exercises, online courses, and practice projects.',
    'Data Analysis': 'The examination and manipulation of data to uncover patterns and insights. Learn by working with datasets, using tools like Excel or Python, and studying statistical methods.',
    'Machine Learning': 'A field of AI that enables systems to learn from data and make predictions. Learn through online courses, hands-on projects, and studying algorithms.',
    'Artificial Intelligence': 'The creation of machines that can perform tasks that typically require human intelligence. Learn by studying AI concepts, working with AI frameworks, and implementing simple AI projects.',
    'Database Management': 'The administration of databases to store and retrieve data efficiently. Learn through database design courses, SQL practice, and working with database management systems.',
    'Software Development': 'The process of designing, coding, testing, and maintaining software applications. Learn through coding practice, studying software engineering principles, and building projects.',
    'Cybersecurity': 'The protection of systems, networks, and data from digital attacks. Learn by studying cybersecurity concepts, practicing ethical hacking, and using security tools.',
    'Cloud Computing': 'The delivery of computing services over the internet. Learn through cloud service provider courses, hands-on labs, and deploying applications in the cloud.',
    'Networking': 'The practice of connecting computers and devices to share resources. Learn by studying networking protocols, setting up networks, and working with network hardware.',
    'Web Development': 'The creation of websites and web applications. Learn by coding in HTML, CSS, and JavaScript, and building projects with web frameworks.',
    'JavaScript': 'A programming language for creating dynamic and interactive web content. Learn by coding in JavaScript, studying online tutorials, and building web applications.',
    'Python': 'A versatile programming language used in various fields like web development, data science, and automation. Learn through coding exercises, online courses, and building projects.',
    'Java': 'A widely-used programming language for building platform-independent applications. Learn by coding in Java, studying object-oriented principles, and building Java projects.',
    'C++': 'A programming language used for system/software development, game programming, and performance-critical applications. Learn through coding practice, studying C++ concepts, and building projects.',
    'SQL': 'A language for managing and manipulating databases. Learn by practicing SQL queries, studying database theory, and working with relational databases.',
    'HTML/CSS': 'The standard languages for creating and styling web pages. Learn by coding in HTML/CSS, studying web design principles, and building web pages.',
    'APIs': 'Application Programming Interfaces allow software to communicate with each other. Learn by studying API documentation, building projects that use APIs, and practicing integration.',
    'Version Control': 'The management of changes to code using systems like Git. Learn through tutorials on Git, practicing with repositories, and collaborating on projects.',
    'Agile Methodologies': 'A set of principles for software development focused on iterative progress. Learn by studying Agile principles, participating in Agile projects, and using tools like Scrum.',
    'DevOps': 'A set of practices that combine software development and IT operations. Learn by studying DevOps tools, practicing CI/CD, and working on deployment projects.',
    'Data Visualization': 'The representation of data in graphical form to make it easier to understand. Learn by using tools like Tableau or PowerBI, and practicing with datasets.',
    'Big Data': 'The processing and analysis of large and complex datasets. Learn through studying big data technologies like Hadoop, practicing with large datasets, and using data processing tools.',
    'Linux': 'An open-source operating system used in servers, desktops, and embedded systems. Learn by using Linux distributions, studying command-line tools, and configuring Linux systems.',
    'Windows': 'A widely-used operating system developed by Microsoft. Learn by using Windows, studying system administration, and configuring Windows environments.',
    'Project Management': 'The discipline of planning, executing, and closing projects. Learn by studying project management frameworks, using tools like Trello or MS Project, and leading small projects.',
    'Systems Design': 'The process of defining the architecture and components of a system. Learn by studying design principles, working on system architecture projects, and using modeling tools.',
    'Embedded Systems': 'Specialized computing systems that are part of larger systems. Learn by studying microcontrollers, programming in C/C++, and building embedded projects.',
    'Algorithms': 'A set of instructions for solving a problem or performing a task. Learn by studying algorithm design, practicing coding problems, and analyzing algorithm efficiency.',
    'Data Structures': 'Ways of organizing and storing data for efficient access and modification. Learn by studying data structures concepts, coding implementations, and solving problems.',
    'Mobile Development': 'The creation of applications for mobile devices. Learn by coding in languages like Swift or Kotlin, using mobile development frameworks, and building apps.',
    'UX/UI Design': 'The design of user interfaces and experiences for software applications. Learn by studying design principles, using design tools like Figma, and prototyping interfaces.',
    'Testing/QA': 'The process of verifying that software meets requirements and is free of defects. Learn by studying testing methodologies, using QA tools, and practicing test case development.',
    'Blockchain': 'A decentralized ledger technology for secure and transparent transactions. Learn by studying blockchain concepts, using blockchain platforms, and building smart contracts.',
    'IT Support': 'Providing assistance and support for IT-related issues. Learn by studying IT support principles, using troubleshooting tools, and practicing with real-world problems.',
    'Business Analysis': 'The practice of identifying business needs and determining solutions. Learn by studying business analysis frameworks, working on case studies, and using analysis tools.',
    'Game Development': 'The creation of video games. Learn by coding in game engines like Unity or Unreal, studying game design principles, and building simple games.',
    'Cloud Services': 'The various services provided by cloud computing platforms. Learn by studying cloud service offerings, practicing with cloud environments, and deploying applications.',
    'Software Architecture': 'The high-level structure of a software system. Learn by studying architecture patterns, working on design projects, and analyzing existing systems.',
    'Scripting': 'The use of scripts to automate tasks. Learn by coding in scripting languages like Python or Bash, and writing scripts for system administration or automation tasks.',
    'Technical Documentation': 'The creation of documents that describe software or systems. Learn by studying documentation best practices, practicing technical writing, and reviewing examples.',
    'Ethical Hacking': 'The practice of testing systems for vulnerabilities in a lawful way. Learn by studying cybersecurity principles, practicing penetration testing, and using hacking tools.',
    'IoT': 'The Internet of Things involves connecting devices to the internet for data exchange. Learn by studying IoT concepts, working with microcontrollers, and building IoT projects.',
    'Virtual Reality': 'A simulated experience that can be similar to or completely different from the real world. Learn by studying VR technologies, using VR development platforms, and building VR experiences.',
    'Augmented Reality': 'Overlaying digital content on the real world. Learn by studying AR concepts, using AR development tools, and creating AR applications.',
    'System Administration': 'The management and maintenance of computer systems and networks. Learn by studying system administration principles, using admin tools, and configuring systems.',
    'Business Intelligence': 'The strategies and technologies used by enterprises for data analysis. Learn by studying BI tools, practicing data analysis, and working with business datasets.',
    'Quantitative Analysis': 'The use of mathematical and statistical modeling in decision-making. Learn by studying quantitative methods, using statistical software, and analyzing data.',
    'Data Engineering': 'The development and maintenance of systems for storing and processing data. Learn by studying data pipelines, working with big data technologies, and building ETL processes.',
    'Computer Vision': 'The field of AI that enables computers to interpret and make decisions based on visual data. Learn by studying computer vision algorithms, using libraries like OpenCV, and working on image processing projects.',
    'Natural Language Processing': 'A field of AI focused on the interaction between computers and human languages. Learn by studying NLP concepts, using tools like NLTK or spaCy, and working on text analysis projects.',
    'Robotics': 'The design and creation of robots. Learn by studying robotics principles, programming microcontrollers, and building robotic systems.',
    'Information Retrieval': 'The process of obtaining information from a large repository. Learn by studying IR techniques, working with search algorithms, and using retrieval systems.',
    'Software Engineering': 'The application of engineering principles to software development. Learn by studying software engineering methodologies, practicing coding, and working on projects.',
    'Network Security': 'The protection of networks from unauthorized access or attacks. Learn by studying security protocols, practicing network security tools, and performing security assessments.',
    'Computer Graphics': 'The creation of visual content using computers. Learn by studying graphics algorithms, using graphics software, and creating visual projects.',
    'Embedded Programming': 'Programming that is specific to embedded systems. Learn by coding in C/C++ for microcontrollers, studying embedded systems concepts, and building small projects.',
    'Data Warehousing': 'The storage of data in a manner optimized for retrieval and analysis. Learn by studying data warehousing concepts, working with ETL tools, and building a data warehouse.',
    'Information Systems': 'The study of systems for managing information. Learn by studying IS concepts, working with database systems, and analyzing business processes.',
    'Technical Support': 'Providing assistance for IT-related issues. Learn by practicing troubleshooting, studying common IT problems, and using support tools.',
    'Product Management': 'The process of managing the lifecycle of a product. Learn by studying product management frameworks, using project management tools, and working on product development projects.',
    'Research & Development': 'The innovation and development of new products or technologies. Learn by studying R&D processes, working on experimental projects, and analyzing market trends.',
    'Digital Marketing': 'The promotion of products or brands using digital technologies. Learn by studying digital marketing strategies, using online marketing tools, and practicing with real-world campaigns.',
    'Algorithm Design': 'The creation of algorithms to solve problems. Learn by studying design principles, practicing coding algorithms, and analyzing efficiency.',
    'Application Development': 'The process of creating software applications. Learn by coding in relevant languages, using development frameworks, and building projects.',
    'Infrastructure Management': 'The management of IT infrastructure to ensure optimal performance. Learn by studying infrastructure components, using management tools, and configuring systems.',
    'Enterprise Solutions': 'Software solutions tailored for large organizations. Learn by studying enterprise architecture, working with enterprise software, and implementing large-scale systems.',
    'Shell Scripting': 'Writing scripts for command-line interfaces to automate tasks. Learn by practicing shell commands, writing scripts, and using scripting in system administration.',
    'Penetration Testing': 'The practice of testing systems for security vulnerabilities. Learn by studying security principles, practicing with penetration testing tools, and performing ethical hacking.',
    'Cryptography': 'The practice of securing information through encryption. Learn by studying cryptographic algorithms, using encryption tools, and implementing secure communication.',
    'Load Balancing': 'Distributing network or application traffic across multiple servers. Learn by studying load balancing algorithms, using tools like NGINX, and configuring load balancers.',
    'Cloud Security': 'Protecting cloud environments from security threats. Learn by studying cloud security practices, using cloud provider tools, and securing cloud applications.',
    'Containerization (Docker, Kubernetes)': 'Packaging applications and their dependencies into containers. Learn by studying containerization concepts, using Docker/Kubernetes, and deploying containerized applications.',
    'CI/CD Pipelines': 'Continuous Integration and Continuous Deployment practices for software. Learn by studying CI/CD tools, building pipelines, and automating deployment processes.',
    'API Development': 'The creation of APIs for software applications. Learn by coding in relevant languages, using API frameworks, and building and documenting APIs.',
    'Cross-Platform Development': 'Developing software that runs on multiple platforms. Learn by studying cross-platform tools, using frameworks like React Native, and building multi-platform applications.',
    'Microservices': 'An architectural style for building modular software systems. Learn by studying microservices principles, working with microservices frameworks, and designing service-oriented applications.',
    'Distributed Systems': 'Systems with components located on different networked computers. Learn by studying distributed system concepts, working on distributed projects, and using relevant tools.',
    'Edge Computing': 'Processing data closer to where it is generated rather than in a centralized data center. Learn by studying edge computing concepts, working with IoT devices, and deploying edge solutions.',
    'Network Architecture': 'The design of networks to support communication and data exchange. Learn by studying networking principles, designing network topologies, and configuring network devices.',
    'Network Protocols': 'Rules that define how data is transmitted over a network. Learn by studying protocol standards, analyzing network traffic, and configuring network services.',
    'Operating Systems': 'Software that manages computer hardware and software resources. Learn by studying OS concepts, working with different OSes, and managing system resources.',
    'Parallel Computing': 'The simultaneous use of multiple compute resources to solve a problem. Learn by studying parallel algorithms, using parallel processing frameworks, and practicing with parallel tasks.',
    'Quantum Computing': 'A new form of computing based on quantum mechanics. Learn by studying quantum algorithms, working with quantum simulators, and exploring quantum programming languages.',
    'Real-Time Systems': 'Systems that require timely processing and response. Learn by studying real-time systems principles, working with real-time operating systems, and developing real-time applications.',
    'Systems Integration': 'The process of bringing together different subsystems into a single system. Learn by studying integration techniques, using middleware, and working on integration projects.',
    'Virtualization': 'The creation of virtual instances of resources like servers or networks. Learn by studying virtualization technologies, using tools like VMware, and practicing with virtual environments.',
    'Data Governance': 'The management of data availability, usability, and security. Learn by studying governance frameworks, implementing policies, and ensuring compliance with regulations.',
    'Data Mining': 'The process of discovering patterns and knowledge from large amounts of data. Learn by studying data mining techniques, using data mining tools, and analyzing datasets.',
    'Data Privacy': 'The protection of personal information from unauthorized access. Learn by studying privacy laws, implementing data protection measures, and ensuring compliance with regulations.',
    'Data Science': 'The field of analyzing and interpreting complex data to drive decisions. Learn by studying statistical methods, using data science tools, and working on data analysis projects.',
    'Data Visualization Tools (Tableau, PowerBI)': 'Tools for creating visual representations of data. Learn by using tools like Tableau or PowerBI, practicing with datasets, and building dashboards.',
    'Data Wrangling': 'The process of cleaning and transforming raw data into a usable format. Learn by practicing data manipulation in Python or R, and working on real-world datasets.',
    'Database Design': 'The process of designing the structure of a database. Learn by studying relational database principles, practicing schema design, and using database management systems.',
    'ETL Processes': 'The extraction, transformation, and loading of data from different sources. Learn by studying ETL tools, practicing with data pipelines, and working on data integration projects.',
    'Machine Learning Engineering': 'The practice of deploying machine learning models into production. Learn by studying deployment techniques, using MLOps tools, and working on production-level ML projects.',
    'Model Deployment': 'The process of deploying machine learning models to a production environment. Learn by using deployment frameworks, practicing with cloud services, and ensuring model scalability.',
    'Model Evaluation': 'Assessing the performance of machine learning models. Learn by studying evaluation metrics, practicing with validation techniques, and comparing model performance.',
    'Neural Networks': 'A class of machine learning models inspired by the human brain. Learn by studying neural network architectures, using deep learning frameworks, and working on image or text projects.',
    'Predictive Analytics': 'The use of data, algorithms, and machine learning techniques to predict future outcomes. Learn by studying predictive models, using statistical software, and analyzing historical data.',
    'Reinforcement Learning': 'A type of machine learning where an agent learns to make decisions by trial and error. Learn by studying RL algorithms, using RL libraries, and building RL projects.',
    'Supervised Learning': 'A type of machine learning where the model is trained on labeled data. Learn by studying supervised algorithms, practicing with labeled datasets, and evaluating model performance.',
    'Unsupervised Learning': 'A type of machine learning where the model learns patterns from unlabeled data. Learn by studying clustering and dimensionality reduction, and working with unlabeled datasets.',
    'Data Quality Assurance': 'The practice of ensuring data integrity, accuracy, and reliability. Learn by studying data validation techniques, using data quality tools, and performing data audits.',
    'Deep Learning': 'A subset of machine learning focusing on neural networks with many layers. Learn by studying deep learning concepts, using frameworks like TensorFlow, and working on complex datasets.',
    'Bioinformatics': 'The application of computer science and statistics to biological data. Learn by studying bioinformatics tools, working with biological datasets, and exploring genomics.',
    'Cheminformatics': 'The use of computer and informational techniques to solve chemical problems. Learn by studying cheminformatics software, analyzing chemical data, and working on drug discovery projects.',
    'Computational Biology': 'The use of computational techniques to analyze biological data. Learn by studying computational models, working with biological data, and exploring molecular biology.',
    'Geographical Information Systems (GIS)': 'Systems used to capture, analyze, and visualize geographical data. Learn by studying GIS tools, working with spatial data, and creating maps.',
    'Human-Computer Interaction': 'The study of how people interact with computers. Learn by studying UX principles, working on user interface design, and conducting usability testing.',
    'Information Security': 'The practice of protecting information from unauthorized access. Learn by studying security principles, implementing security measures, and practicing with security tools.',
    'Software Configuration Management': 'The practice of tracking and controlling changes in software. Learn by studying SCM tools, using version control systems, and managing software builds.',
    'Supply Chain Management': 'The management of the flow of goods and services. Learn by studying SCM concepts, working on logistics projects, and using supply chain software.',
    'Telecommunications': 'The transmission of information over distances. Learn by studying telecom technologies, working with communication protocols, and configuring network devices.',
    'Technical Writing': 'The practice of creating instructional and informational documents. Learn by studying writing techniques, practicing technical documentation, and reviewing examples.',
    'User Research': 'The study of users to inform design and product decisions. Learn by studying research methods, conducting user interviews, and analyzing user data.',
    'User Testing': 'The process of evaluating a product by testing it with real users. Learn by studying testing techniques, conducting usability tests, and analyzing feedback.'
}




# skills needed for each career

career_skills = {
    'Software Engineer': ['Programming', 'Software Development', 'Algorithms', 'Data Structures', 'Version Control', 'Systems Design', 'Testing/QA', 'Project Management'],
    'Data Scientist': ['Data Analysis', 'Machine Learning', 'Data Visualization', 'Big Data', 'Python', 'SQL', 'Data Wrangling', 'Statistical Analysis'],
    'Systems Analyst': ['Systems Design', 'Database Management', 'Project Management', 'Business Analysis', 'Information Systems', 'Technical Documentation', 'APIs', 'Data Analysis'],
    'Web Developer': ['Web Development', 'JavaScript', 'HTML/CSS', 'APIs', 'Version Control', 'Testing/QA', 'User Experience (UX)', 'Responsive Design'],
    'Database Administrator': ['Database Management', 'SQL', 'Data Warehousing', 'Database Design', 'ETL Processes', 'Data Privacy', 'Systems Administration', 'Backup and Recovery'],
    'Network Engineer': ['Networking', 'Network Security', 'Network Architecture', 'Linux', 'Windows', 'Cloud Computing', 'Load Balancing', 'Network Protocols'],
    'Cybersecurity Analyst': ['Cybersecurity', 'Penetration Testing', 'Network Security', 'Cryptography', 'Ethical Hacking', 'Information Security', 'Threat Analysis', 'Incident Response'],
    'Machine Learning Engineer': ['Machine Learning', 'Programming', 'Data Analysis', 'Neural Networks', 'Model Deployment', 'Predictive Analytics', 'Python', 'Data Structures'],
    'Cloud Architect': ['Cloud Computing', 'Cloud Services', 'Infrastructure Management', 'Virtualization', 'Containerization (Docker, Kubernetes)', 'Networking', 'Cloud Security', 'DevOps'],
    'DevOps Engineer': ['DevOps', 'CI/CD Pipelines', 'Containerization (Docker, Kubernetes)', 'Scripting', 'Cloud Computing', 'Linux', 'Infrastructure Management', 'Automation Tools'],
    'Front-End Developer': ['Web Development', 'JavaScript', 'HTML/CSS', 'APIs', 'UI/UX Design', 'Responsive Design', 'Version Control', 'Testing/QA'],
    'Back-End Developer': ['Programming', 'APIs', 'Database Management', 'Server Management', 'Algorithms', 'Security', 'Version Control', 'Cloud Services'],
    'Full Stack Developer': ['Programming', 'Web Development', 'JavaScript', 'HTML/CSS', 'APIs', 'Database Management', 'Version Control', 'DevOps'],
    'AI Research Scientist': ['Artificial Intelligence', 'Machine Learning', 'Programming', 'Neural Networks', 'Natural Language Processing', 'Algorithms', 'Python', 'Research & Development'],
    'Game Developer': ['Game Development', 'Programming', 'Computer Graphics', 'C++', '3D Modeling', 'Physics Simulations', 'Algorithms', 'UI/UX Design'],
    'Mobile App Developer': ['Mobile Development', 'Programming', 'Java', 'APIs', 'UI/UX Design', 'Testing/QA', 'Version Control', 'App Deployment'],
    'IT Support Specialist': ['IT Support', 'Technical Support', 'Networking', 'System Administration', 'Troubleshooting', 'Windows', 'Linux', 'Technical Documentation'],
    'Business Intelligence Analyst': ['Business Intelligence', 'Data Analysis', 'Data Visualization', 'SQL', 'Data Warehousing', 'Reporting Tools', 'Quantitative Analysis', 'Database Management'],
    'Embedded Systems Engineer': ['Embedded Systems', 'C++', 'Microcontrollers', 'Assembly Language', 'Systems Design', 'Embedded Programming', 'Scripting', 'Real-Time Systems'],
    'IT Project Manager': ['Project Management', 'Systems Design', 'Agile Methodologies', 'Business Analysis', 'Technical Documentation', 'Software Development', 'Budget Management', 'Team Leadership'],
    'UX/UI Designer': ['UX/UI Design', 'User Research', 'Prototyping', 'Wireframing', 'HTML/CSS', 'Responsive Design', 'Interaction Design', 'Visual Design'],
    'Technical Writer': ['Technical Documentation', 'Technical Writing', 'Information Systems', 'APIs', 'Software Development', 'User Manuals', 'Research', 'Editing'],
    'Blockchain Developer': ['Blockchain', 'Cryptography', 'Programming', 'Smart Contracts', 'Distributed Systems', 'Security', 'APIs', 'Testing/QA'],
    'IT Consultant': ['Business Analysis', 'Systems Design', 'Project Management', 'IT Support', 'Networking', 'Software Development', 'Cloud Computing', 'Technical Documentation'],
    'Data Engineer': ['Data Engineering', 'Database Management', 'ETL Processes', 'Data Warehousing', 'Big Data', 'Programming', 'SQL', 'Data Quality Assurance'],
    'Quantitative Analyst': ['Quantitative Analysis', 'Data Analysis', 'Machine Learning', 'Programming', 'Statistical Analysis', 'Financial Modeling', 'Python', 'Algorithms'],
    'Data Architect': ['Data Architecture', 'Database Design', 'Data Warehousing', 'SQL', 'ETL Processes', 'Data Governance', 'Big Data', 'Data Modeling'],
    'Systems Administrator': ['System Administration', 'Networking', 'Linux', 'Windows', 'Cloud Computing', 'Scripting', 'Security', 'Backup and Recovery'],
    'Site Reliability Engineer': ['DevOps', 'Systems Design', 'Monitoring & Alerting', 'Automation Tools', 'Cloud Computing', 'Linux', 'CI/CD Pipelines', 'Scripting'],
    'AR/VR Developer': ['Augmented Reality', 'Virtual Reality', '3D Modeling', 'Game Development', 'UI/UX Design', 'Programming', 'Computer Graphics', 'Physics Simulations'],
    'Ethical Hacker': ['Ethical Hacking', 'Penetration Testing', 'Cybersecurity', 'Network Security', 'Cryptography', 'Operating Systems', 'Programming', 'Web Security'],
    'Digital Marketer': ['Digital Marketing', 'SEO', 'Content Creation', 'Data Analysis', 'Social Media Marketing', 'Web Analytics', 'Email Marketing', 'Pay-Per-Click Advertising'],
    'Software Development Manager': ['Software Development', 'Project Management', 'Agile Methodologies', 'Team Leadership', 'Systems Design', 'Technical Documentation', 'Software Architecture', 'Budget Management'],
    'Product Manager': ['Product Management', 'Project Management', 'Business Analysis', 'Technical Documentation', 'Agile Methodologies', 'UI/UX Design', 'Market Research', 'Team Leadership'],
    'Network Security Engineer': ['Network Security', 'Cybersecurity', 'Penetration Testing', 'Network Architecture', 'Firewall Configuration', 'Cryptography', 'Network Protocols', 'Operating Systems'],
    'IT Auditor': ['Information Systems', 'Cybersecurity', 'Regulatory Compliance', 'Technical Documentation', 'Risk Management', 'Auditing', 'Project Management', 'Data Privacy'],
    'Technical Support Specialist': ['Technical Support', 'IT Support', 'Troubleshooting', 'Networking', 'System Administration', 'Windows', 'Linux', 'Technical Documentation'],
    'Algorithm Engineer': ['Algorithm Design', 'Programming', 'Data Structures', 'Machine Learning', 'Artificial Intelligence', 'Mathematics', 'Optimization Techniques', 'C++'],
    'Applications Developer': ['Application Development', 'Programming', 'Software Development', 'APIs', 'Testing/QA', 'Database Management', 'UI/UX Design', 'Mobile Development'],
    'Research Scientist': ['Research & Development', 'Programming', 'Artificial Intelligence', 'Data Analysis', 'Machine Learning', 'Algorithms', 'Technical Writing', 'Statistics'],
    'Computer Vision Engineer': ['Computer Vision', 'Machine Learning', 'Deep Learning', 'Programming', 'Python', 'Algorithms', 'Data Analysis', 'Image Processing'],
    'Software Quality Assurance Engineer': ['Testing/QA', 'Software Development', 'Automation Tools', 'Programming', 'Bug Tracking', 'Agile Methodologies', 'Technical Documentation', 'CI/CD Pipelines'],
    'Chief Technology Officer (CTO)': ['Leadership', 'Technical Strategy', 'Project Management', 'Systems Design', 'Software Development', 'Cloud Computing', 'IT Infrastructure', 'Business Analysis'],
    'Network Architect': ['Networking', 'Network Architecture', 'Cloud Computing', 'Network Security', 'Load Balancing', 'Linux', 'Firewall Configuration', 'Virtualization'],
    'DevSecOps Engineer': ['DevOps', 'Cybersecurity', 'CI/CD Pipelines', 'Cloud Security', 'Containerization (Docker, Kubernetes)', 'Scripting', 'Automation Tools', 'Network Security'],
    'Robotics Engineer': ['Robotics', 'Programming', 'Algorithms', 'Machine Learning', 'Embedded Systems', 'C++', 'Control Systems', 'Mechatronics'],
    'Bioinformatics Specialist': ['Bioinformatics', 'Programming', 'Data Analysis', 'Machine Learning', 'Computational Biology', 'Data Visualization', 'Python', 'Genomics'],
    'Data Warehouse Architect': ['Data Warehousing', 'Database Management', 'ETL Processes', 'SQL', 'Data Architecture', 'Big Data', 'Cloud Computing', 'Data Governance'],
    'Cloud Security Engineer': ['Cloud Security', 'Cybersecurity', 'Cloud Computing', 'Network Security', 'Firewall Configuration', 'Cryptography', 'Identity Management', 'Penetration Testing'],
    'Big Data Engineer': ['Big Data', 'Data Engineering', 'Hadoop', 'Spark', 'Data Warehousing', 'ETL Processes', 'SQL', 'Programming'],
    'Information Security Analyst': ['Cybersecurity', 'Information Security', 'Threat Analysis', 'Incident Response', 'Penetration Testing', 'Network Security', 'Cryptography', 'Operating Systems'],
    'IT Operations Manager': ['IT Support', 'System Administration', 'Project Management', 'Technical Support', 'Networking', 'Cloud Computing', 'Troubleshooting', 'Budget Management'],
    'IoT Developer': ['IoT', 'Embedded Systems', 'Networking', 'Programming', 'Sensors & Actuators', 'Data Analysis', 'Cloud Computing', 'Security'],
    'Digital Forensics Analyst': ['Cybersecurity', 'Digital Forensics', 'Incident Response', 'Penetration Testing', 'Cryptography', 'Network Security', 'Information Security', 'Technical Documentation'],
    'Systems Engineer': ['Systems Design', 'Systems Integration', 'Programming', 'Project Management', 'Networking', 'Cloud Computing', 'Scripting', 'Testing/QA'],
    'Database Developer': ['Database Management', 'SQL', 'Database Design', 'ETL Processes', 'Data Warehousing', 'Programming', 'Data Security', 'APIs'],
    'Information Systems Manager': ['Information Systems', 'Project Management', 'Systems Design', 'Database Management', 'Networking', 'IT Support', 'Cybersecurity', 'Team Leadership'],
    'ERP Consultant': ['Enterprise Solutions', 'Database Management', 'Business Analysis', 'Project Management', 'SQL', 'Software Development', 'System Integration', 'Technical Documentation'],
    'Geographic Information Systems (GIS) Specialist': ['GIS', 'Data Analysis', 'Mapping', 'Spatial Data', 'Programming', 'Cartography', 'Data Visualization', 'Remote Sensing'],
    'Telecommunications Engineer': ['Telecommunications', 'Networking', 'Signal Processing', 'Network Security', 'Programming', 'Systems Design', 'Cloud Computing', 'Network Protocols'],
    'Cryptography Engineer': ['Cryptography', 'Cybersecurity', 'Mathematics', 'Programming', 'Network Security', 'Blockchain', 'Penetration Testing', 'Quantum Computing'],
    'Natural Language Processing (NLP) Engineer': ['Natural Language Processing', 'Machine Learning', 'Python', 'Deep Learning', 'Text Mining', 'Data Analysis', 'Artificial Intelligence', 'Algorithms'],
    'Game Designer': ['Game Development', 'UI/UX Design', 'Prototyping', 'Level Design', 'Programming', 'Storyboarding', '3D Modeling', 'Testing/QA'],
    'Simulation Engineer': ['Simulation', 'Programming', 'Modeling', 'Physics Simulations', 'Data Analysis', 'Algorithms', 'Testing/QA', 'Research & Development'],
    'Data Privacy Officer': ['Data Privacy', 'Data Governance', 'Cybersecurity', 'Legal Compliance', 'Risk Management', 'Data Security', 'Technical Documentation', 'Information Systems'],
    'Cybercrime Analyst': ['Cybersecurity', 'Digital Forensics', 'Incident Response', 'Penetration Testing', 'Information Security', 'Network Security', 'Cryptography', 'Threat Analysis'],
    'Software Test Engineer': ['Testing/QA', 'Software Development', 'Automation Tools', 'Bug Tracking', 'Scripting', 'Programming', 'CI/CD Pipelines', 'Agile Methodologies'],
    'Digital Transformation Consultant': ['Business Analysis', 'Project Management', 'IT Strategy', 'Cloud Computing', 'Systems Design', 'Technical Documentation', 'Agile Methodologies', 'Change Management'],
    'Cloud Solutions Consultant': ['Cloud Computing', 'Cloud Services', 'Infrastructure Management', 'Networking', 'Cloud Security', 'DevOps', 'Project Management', 'Technical Documentation'],
    'Augmented Reality Engineer': ['Augmented Reality', 'Programming', '3D Modeling', 'Computer Graphics', 'Game Development', 'User Experience (UX)', 'Machine Learning', 'Testing/QA'],
    'Virtual Reality Architect': ['Virtual Reality', 'Programming', '3D Modeling', 'Computer Graphics', 'Game Development', 'Algorithms', 'UX/UI Design', 'Testing/QA'],
    'User Experience Researcher': ['User Research', 'UX/UI Design', 'Prototyping', 'User Testing', 'Interaction Design', 'Behavioral Science', 'Data Analysis', 'Technical Documentation'],
    'Network Analyst': ['Networking', 'Network Security', 'Data Analysis', 'System Monitoring', 'Incident Response', 'Network Protocols', 'Cloud Computing', 'Firewall Configuration'],
    'System Integration Engineer': ['Systems Integration', 'Systems Design', 'APIs', 'Networking', 'Cloud Computing', 'Project Management', 'Programming', 'Data Migration'],
    'IT Trainer': ['IT Support', 'Training', 'Technical Documentation', 'User Support', 'Technical Writing', 'Troubleshooting', 'Software Development', 'Project Management'],
    'API Developer': ['APIs', 'Programming', 'Web Development', 'Security', 'Database Management', 'Cloud Computing', 'Testing/QA', 'Documentation'],
    'Middleware Engineer': ['Middleware', 'Systems Integration', 'Programming', 'APIs', 'Database Management', 'Security', 'Cloud Computing', 'Project Management'],
    'Artificial Intelligence Engineer': ['Artificial Intelligence', 'Machine Learning', 'Neural Networks', 'Programming', 'Data Analysis', 'Python', 'Algorithms', 'Computer Vision'],
    'Data Governance Analyst': ['Data Governance', 'Data Privacy', 'Cybersecurity', 'Database Management', 'Data Quality Assurance', 'Compliance', 'Information Systems', 'Technical Documentation'],
    'Mobile Security Specialist': ['Mobile Development', 'Cybersecurity', 'Encryption', 'Penetration Testing', 'Operating Systems', 'Programming', 'Network Security', 'Mobile App Security'],
    'Technical Evangelist': ['Technical Writing', 'Programming', 'Public Speaking', 'Software Development', 'Content Creation', 'Social Media', 'Blogging', 'Community Engagement'],
    'Business Systems Analyst': ['Business Analysis', 'Systems Design', 'Database Management', 'Project Management', 'Technical Documentation', 'IT Support', 'APIs', 'Business Intelligence'],
    'Computational Linguist': ['Natural Language Processing', 'Machine Learning', 'Programming', 'Linguistics', 'Artificial Intelligence', 'Data Analysis', 'Python', 'Text Mining'],
    'Firmware Engineer': ['Embedded Systems', 'Programming', 'C++', 'Microcontrollers', 'Systems Design', 'Real-Time Systems', 'Scripting', 'Testing/QA'],
    'High-Performance Computing (HPC) Engineer': ['Parallel Computing', 'Programming', 'Cluster Computing', 'Linux', 'Optimization Techniques', 'Algorithms', 'Data Analysis', 'Systems Design'],
    'IT Compliance Manager': ['Regulatory Compliance', 'Information Security', 'Risk Management', 'Technical Documentation', 'Auditing', 'Project Management', 'Data Privacy', 'Cybersecurity'],
    'Machine Learning Architect': ['Machine Learning', 'Programming', 'Model Deployment', 'Big Data', 'Cloud Computing', 'Neural Networks', 'Data Engineering', 'Data Analysis'],
    'Microservices Architect': ['Microservices', 'Software Architecture', 'Programming', 'APIs', 'Containerization (Docker, Kubernetes)', 'Cloud Computing', 'DevOps', 'Security'],
    'Quantum Computing Engineer': ['Quantum Computing', 'Programming', 'Algorithms', 'Physics', 'Parallel Computing', 'Data Analysis', 'Cryptography', 'Research & Development'],
    'Robotic Process Automation (RPA) Developer': ['RPA', 'Programming', 'Automation Tools', 'APIs', 'Workflow Automation', 'Scripting', 'Data Analysis', 'Process Optimization'],
    'Security Architect': ['Cybersecurity', 'Network Security', 'Systems Design', 'Cryptography', 'Penetration Testing', 'Information Security', 'Risk Management', 'Firewall Configuration'],
    'Software Deployment Engineer': ['Software Development', 'CI/CD Pipelines', 'DevOps', 'Automation Tools', 'Programming', 'Scripting', 'System Administration', 'Testing/QA'],
    'Solutions Architect': ['Systems Design', 'Cloud Computing', 'Software Architecture', 'Networking', 'Project Management', 'Security', 'APIs', 'Technical Documentation'],
    'Telecommunication Systems Engineer': ['Telecommunications', 'Networking', 'Signal Processing', 'Network Security', 'Cloud Computing', 'Programming', 'Systems Design', 'Network Protocols'],
    'UI/UX Researcher': ['User Research', 'UX/UI Design', 'Prototyping', 'User Testing', 'Behavioral Science', 'Data Analysis', 'Wireframing', 'Technical Documentation'],
    'Web Content Manager': ['Content Creation', 'Web Development', 'SEO', 'Digital Marketing', 'CMS', 'JavaScript', 'HTML/CSS', 'Data Analysis'],
    'Web Security Administrator': ['Web Development', 'Cybersecurity', 'Penetration Testing', 'Web Security', 'APIs', 'Network Security', 'Cryptography', 'Firewall Configuration'],
    'Wireless Network Engineer': ['Networking', 'Network Security', 'Wireless Technologies', 'Cloud Computing', 'Firewall Configuration', 'Linux', 'Network Protocols', 'Network Architecture'],
    'Cloud DevOps Engineer': ['DevOps', 'Cloud Computing', 'CI/CD Pipelines', 'Containerization (Docker, Kubernetes)', 'Scripting', 'Automation Tools', 'Infrastructure Management', 'Security'],
    'Data Quality Manager': ['Data Quality Assurance', 'Data Governance', 'Data Privacy', 'Data Analysis', 'Data Warehousing', 'ETL Processes', 'SQL', 'Compliance'],
    'E-commerce Developer': ['Web Development', 'APIs', 'JavaScript', 'HTML/CSS', 'Database Management', 'Payment Gateway Integration', 'Security', 'UI/UX Design'],
    'Fintech Developer': ['Blockchain', 'APIs', 'Cryptography', 'Security', 'Programming', 'Database Management', 'Payment Systems', 'Regulatory Compliance'],
    'IT Risk Manager': ['Risk Management', 'Cybersecurity', 'Compliance', 'Project Management', 'Information Security', 'Technical Documentation', 'Auditing', 'Incident Response']
}

# initialize dataframe
skillCol = list(skill_descriptions.keys())
careerCol = list(career_skills.keys())
df = pd.DataFrame(columns=skillCol + ['Career'])
skillsDf = pd.DataFrame(list(skill_descriptions.items()), columns=['Skill', 'Description'])
skills = skillsDf['Skill'].values
# generate random data
np.random.seed(0)
for i in range(num_rows):
    career = np.random.choice(careerCol)

    # random proficiency for normal skills
    proficiency = np.random.randint(1, 6, size=len(skillCol))
    
    # higher proficiency for career skills
    if career in career_skills:
        skill_indices = [np.where(skills == skill)[0][0] for skill in career_skills[career] if skill in skills]
        proficiency[skill_indices] = np.random.randint(7, 11, size=len(skill_indices))
    df.loc[i] = list(proficiency) + [career]

# encode careers
filtered_df = df.copy()
label_encoder = LabelEncoder()
filtered_df['EncodeCareer'] = label_encoder.fit_transform(filtered_df['Career'])

# save to csv
filtered_df.to_csv('career_skills_dataset_with_pattern.csv', index=False)
df.to_csv('career_skills_dataset.csv', index=False)
skillsDf.to_csv('skill_descriptions.csv', index=False)